#!/usr/bin/env python3
"""
Generate SKILLS_INDEX.md by reading metadata.yaml files under skills/.

Usage:
    python tools/generate_index.py
"""

from datetime import date
from pathlib import Path

import yaml

REPO_ROOT = Path(__file__).resolve().parent.parent
SKILLS_ROOT = REPO_ROOT / "skills"
INDEX_PATH = REPO_ROOT / "SKILLS_INDEX.md"

STATUS_EMOJI = {
    "stable": "🟢",
    "beta": "🟡",
    "deprecated": "🔴",
    "archived": "⚪",
}


def collect_tier(tier):
    rows = []
    tier_dir = SKILLS_ROOT / tier
    if not tier_dir.exists():
        return rows
    for skill_dir in sorted(tier_dir.iterdir()):
        meta_path = skill_dir / "metadata.yaml"
        if not meta_path.exists():
            continue
        try:
            meta = yaml.safe_load(meta_path.read_text(encoding="utf-8")) or {}
        except yaml.YAMLError:
            continue
        rows.append({
            "name": meta.get("name", skill_dir.name),
            "version": meta.get("version", "—"),
            "status": meta.get("status", "beta"),
            "tags": meta.get("tags", []) or [],
            "last_updated": meta.get("last_updated", "—"),
            "path": skill_dir.relative_to(REPO_ROOT).as_posix(),
        })
    return rows


def render_table(rows):
    if not rows:
        return None
    out = ["| Skill | Version | Status | Tags | Last Updated |",
           "|-------|---------|--------|------|--------------|"]
    for r in rows:
        emoji = STATUS_EMOJI.get(r["status"], "")
        status_cell = f"{emoji} {r['status']}".strip()
        tags = ", ".join(r["tags"]) if r["tags"] else "—"
        out.append(
            f"| [{r['name']}]({r['path']}/) | {r['version']} | {status_cell} | "
            f"{tags} | {r['last_updated']} |"
        )
    return "\n".join(out)


def main():
    contributed = collect_tier("contributed")
    curated = collect_tier("curated")
    total = len(contributed) + len(curated)
    today = date.today().isoformat()

    parts = [
        "# Claude Skills Library — Index",
        "",
        f"> Auto-generated on {today} | Total: {total} skills",
        "",
        "## Contributed Skills",
        "",
    ]
    contrib_table = render_table(contributed)
    parts.append(contrib_table or "_No contributed skills yet._")
    parts.extend([
        "",
        "## Curated Skills",
        "",
    ])
    curated_table = render_table(curated)
    parts.append(
        curated_table
        or "_No curated skills yet. [See curation policy](docs/CURATION_POLICY.md)._"
    )
    parts.extend([
        "",
        "---",
        "*Generated by [tools/generate_index.py](tools/generate_index.py)*",
        "",
    ])

    INDEX_PATH.write_text("\n".join(parts), encoding="utf-8")
    print(f"Wrote {INDEX_PATH.relative_to(REPO_ROOT)} ({total} skills)")


if __name__ == "__main__":
    main()
